apiVersion: apps/v1
kind: Deployment
metadata:
  name: stay-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: stay-container
          image: nginx:latest
          ports:
            - containerPort: 8080
